include(joinpath(@__DIR__, "draw_design.jl"))
include(joinpath(@__DIR__, "winners.jl"))
include(joinpath(@__DIR__, "oracle.jl"))
include(joinpath(@__DIR__, "common_marginals_moments.jl"))
include(joinpath(@__DIR__, "common_marginals_interval.jl"))
include(joinpath(@__DIR__, "instrumentation.jl"))
include(joinpath(@__DIR__, "oracle_fast.jl"))
include(joinpath(@__DIR__, "gravity_elimination.jl"))
include(joinpath(@__DIR__, "three_way_derivatives.jl"))
include(joinpath(@__DIR__, "lfix_incremental.jl"))
include(joinpath(@__DIR__, "composite_gradient.jl"))
include(joinpath(@__DIR__, "composite_gradient_fast.jl"))
include(joinpath(@__DIR__, "cm_lookup_kernels.jl"))
include(joinpath(@__DIR__, "lfix_cm_aware.jl"))
include(joinpath(@__DIR__, "cm_hessian_architectures.jl"))
include(joinpath(@__DIR__, "cm_production_bundle.jl"))
include(joinpath(@__DIR__, "cm_screen_bridge.jl"))
include(joinpath(@__DIR__, "gradient_workspace.jl"))
include(joinpath(@__DIR__, "lfix_factorized.jl"))
include(joinpath(@__DIR__, "lfix_factorized_workspace.jl"))
include(joinpath(@__DIR__, "lfix_cm_cplus.jl"))
include(joinpath(@__DIR__, "nested_quantile_grids.jl"))
include(joinpath(@__DIR__, "cm_outer_driver.jl"))
include(joinpath(@__DIR__, "cm_config.jl"))
include(joinpath(@__DIR__, "cm_meanzc_moments.jl"))
include(joinpath(@__DIR__, "cm_meanzc_config.jl"))
include(joinpath(@__DIR__, "cm_meanzc_production.jl"))
include(joinpath(@__DIR__, "cm_meanzc_cplus.jl"))
include(joinpath(@__DIR__, "cm_frechet_level.jl"))
include(joinpath(@__DIR__, "cm_frechet_hessian.jl"))
include(joinpath(@__DIR__, "cm_frechet_hessian_threaded.jl"))
include(joinpath(@__DIR__, "cm_frechet_cplus.jl"))
include(joinpath(@__DIR__, "cm_checkpoint.jl"))
include(joinpath(@__DIR__, "production_backend_manifest.jl"))


lp(xs...) = (println(xs...); flush(stdout))
const FAILURES = String[]
check(cond, name) = (lp(cond ? "PASS  " : "FAIL  ", name); cond || push!(FAILURES, name))

ctx = d4_exact_setup(δ = 1.0, find_smallest = true, needs_outer_moment_jacobian = false)

pcx1 = build_cm_production_context(ctx, CS; L = 10, contrasts = :anchored)
m1 = resolve_flexible_cm_manifest(cctx = pcx1.cctx, blas_threads = nothing)
check(pcx1.cctx.R === nothing, "flexible-CM, :anchored: cctx.R is nothing (as expected)")
check(m1.restriction_hessian_backend == :cm_bin_prefix, "flexible-CM, :anchored: label = :cm_bin_prefix (no congruence)")

pcx2 = build_cm_production_context(ctx, CS; L = 10, contrasts = :orthonormal)
m2 = resolve_flexible_cm_manifest(cctx = pcx2.cctx, blas_threads = nothing)
check(pcx2.cctx.R !== nothing, "flexible-CM, :orthonormal: cctx.R is NOT nothing (as expected)")
check(m2.restriction_hessian_backend == :cm_bin_prefix_plus_congruence, "flexible-CM, :orthonormal: label = :cm_bin_prefix_plus_congruence")

pcx3 = build_cm_meanzc_production_context(ctx, CS; L = 10, K_mean = 1, K_pair = 1, contrasts = :anchored)
m3 = resolve_flexible_cm_manifest(cctx = pcx3.cctx, blas_threads = nothing, cm_extension = :cm_plus_equal_means_zero_covariance, meanzc_K_mean = 1, meanzc_K_pair = 1)
check(pcx3.cctx.R === nothing, "CM+ZC, :anchored (production default): cctx.R is nothing")
check(m3.restriction_hessian_backend == :cm_bin_prefix, "CM+ZC, :anchored (production default): label is now :cm_bin_prefix, NOT :cm_bin_prefix_plus_congruence (THE BUG THIS FIXES -- old code claimed congruence here based on is_meanzc alone)")

lp("==================== SUMMARY ====================")
if isempty(FAILURES)
    lp("ALL PASS")
else
    lp("FAILURES: ", FAILURES)
    exit(1)
end
